services:
  db:
    image: mysql:8.0 
    restart: always 
    environment: 
      MYSQL_ROOT_PASSWORD: root_password_segura 
      MYSQL_DATABASE: banco_rfid_escola 
      MYSQL_USER: usuario_escola 
      MYSQL_PASSWORD: senha_aplicacao_segura 
    volumes:
      - db_data:/var/lib/mysql 
    ports:
      - "3306:3306" 


  app:
    build: . 
    restart: always 
    ports:
      - "5000:5000"
    depends_on: 
      - db
    environment: 
     
      DATABASE_URL: mysql+pymysql://usuario_escola:senha_aplicacao_segura@db/banco_rfid_escola
      FLASK_APP: app.py 
      FLASK_ENV: development 

volumes:
  db_data: 

